package proactive.messages;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.HashMap;

import server.SecretShare;

public class SendVerifierMessage extends InternalPRSServerMessage implements
		Serializable {



	/**
	 * 
	 */
	private static final long serialVersionUID = 8794330652213445246L;

	// Secret generated by the sending server
	private BigInteger verifier;

	private int senderId;

	public SendVerifierMessage(BigInteger verifier, int senderId) {
		super();
		this.verifier = verifier;
		this.senderId = senderId;
	}

	public BigInteger getVerifier() {
		return verifier;
	}

	public void setVerifier(BigInteger verifier) {
		this.verifier = verifier;
	}

	public int getSenderId() {
		return senderId;
	}

	public void setSenderId(int senderId) {
		this.senderId = senderId;
	}
}
